# Generated by Django 4.2.6 on 2023-12-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_webpages_webpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecords',
            old_name='webpages',
            new_name='name',
        ),
    ]
